import fs from "node:fs/promises";
import packageJson from "../package.json";

const { name, version } = packageJson;

const template = `
// This file is generated by the code-gen-meta.ts script. Do not modify this file directly.

export const packageName = "${name}";

export const packageVersion = "${version}";
`.trimEnd();

async function main() {
	await fs.writeFile("src/meta.ts", template, "utf8");
}

void (await main());
